"""
Credit Risk Intelligence Lab
Streamlit Dashboard

This app is the presentation layer of the credit risk analytics pipeline.
It consumes the outputs generated by the notebooks:

01_exploratory_data_analysis.ipynb
02_feature_engineering.ipynb
03_probability_of_default_model.ipynb
04_unsupervised_risk_segmentation.ipynb
05_anomaly_detection.ipynb
06_model_interpretability.ipynb
07_portfolio_risk_reporting.ipynb
08_stress_testing.ipynb

Run from the project root:

    streamlit run app/streamlit_app.py
"""

from __future__ import annotations

from pathlib import Path
from typing import Optional

import numpy as np
import pandas as pd
import streamlit as st


# ---------------------------------------------------------------------
# Page configuration
# ---------------------------------------------------------------------

st.set_page_config(
    page_title="Credit Risk Intelligence Lab",
    page_icon="📊",
    layout="wide",
    initial_sidebar_state="expanded",
)


# ---------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------

APP_DIR = Path(__file__).resolve().parent
PROJECT_ROOT = APP_DIR.parent

DATA_PROCESSED = PROJECT_ROOT / "data" / "processed"
REPORTS_DIR = PROJECT_ROOT / "reports"
REPORTS_TABLES = REPORTS_DIR / "tables"
REPORTS_FIGURES = REPORTS_DIR / "figures"
MODELS_DIR = PROJECT_ROOT / "models"


# ---------------------------------------------------------------------
# Styling
# ---------------------------------------------------------------------

st.markdown(
    """
    <style>
        .main-title {
            font-size: 2.4rem;
            font-weight: 750;
            letter-spacing: -0.03em;
            margin-bottom: 0.1rem;
        }

        .subtitle {
            font-size: 1.05rem;
            color: #666;
            margin-bottom: 1.6rem;
        }

        .section-caption {
            color: #666;
            font-size: 0.96rem;
            line-height: 1.55;
        }

        .metric-card {
            border: 1px solid rgba(49, 51, 63, 0.15);
            border-radius: 14px;
            padding: 1rem 1rem;
            background: rgba(250, 250, 250, 0.65);
        }

        .risk-note {
            border-left: 4px solid #999;
            padding-left: 1rem;
            color: #444;
            line-height: 1.55;
        }

        div[data-testid="stMetricValue"] {
            font-size: 1.65rem;
        }
    </style>
    """,
    unsafe_allow_html=True,
)


# ---------------------------------------------------------------------
# Utility functions
# ---------------------------------------------------------------------

@st.cache_data(show_spinner=False)
def load_csv(path: Path, index_col: Optional[int] = 0) -> Optional[pd.DataFrame]:
    """Load a CSV file safely. Return None if the file does not exist."""
    if not path.exists():
        return None
    try:
        return pd.read_csv(path, index_col=index_col)
    except Exception as exc:
        st.warning(f"Could not load {path.name}: {exc}")
        return None


def format_number(value: float) -> str:
    if pd.isna(value):
        return "N/A"
    return f"{value:,.2f}"


def format_percent(value: float) -> str:
    if pd.isna(value):
        return "N/A"
    return f"{value:.2%}"


def metric_value(df: Optional[pd.DataFrame], metric_name: str) -> Optional[float]:
    if df is None or df.empty:
        return None
    if "metric" not in df.columns or "value" not in df.columns:
        return None

    matched = df.loc[df["metric"] == metric_name, "value"]
    if matched.empty:
        return None

    try:
        return float(matched.iloc[0])
    except Exception:
        return None


def show_missing_outputs_message() -> None:
    st.error(
        "No se encontró el archivo principal `data/processed/credit_risk_portfolio_report.csv`."
    )
    st.markdown(
        """
        Para usar el dashboard, primero ejecuta los notebooks en orden hasta el número 7:

        ```text
        01_exploratory_data_analysis.ipynb
        02_feature_engineering.ipynb
        03_probability_of_default_model.ipynb
        04_unsupervised_risk_segmentation.ipynb
        05_anomaly_detection.ipynb
        06_model_interpretability.ipynb
        07_portfolio_risk_reporting.ipynb
        ```

        Para activar también la pestaña de stress testing, ejecuta:

        ```text
        08_stress_testing.ipynb
        ```
        """
    )


def safe_bar_chart(
    data: pd.DataFrame,
    x_col: str,
    y_col: str,
    title: str,
    y_label: str,
) -> None:
    chart_data = data[[x_col, y_col]].dropna().set_index(x_col)
    st.markdown(f"#### {title}")
    st.bar_chart(chart_data, y=y_col)
    st.caption(y_label)


def dataframe_download_button(
    df: pd.DataFrame,
    label: str,
    file_name: str,
) -> None:
    csv = df.to_csv(index=True).encode("utf-8")
    st.download_button(
        label=label,
        data=csv,
        file_name=file_name,
        mime="text/csv",
    )


# ---------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------

portfolio_report = load_csv(DATA_PROCESSED / "credit_risk_portfolio_report.csv", index_col=0)
portfolio_kpis = load_csv(REPORTS_TABLES / "07_portfolio_kpis.csv", index_col=None)
risk_band_summary = load_csv(REPORTS_TABLES / "07_risk_band_summary.csv", index_col=0)
cluster_summary = load_csv(REPORTS_TABLES / "07_cluster_portfolio_summary.csv", index_col=0)
anomaly_summary = load_csv(REPORTS_TABLES / "07_anomaly_portfolio_summary.csv", index_col=0)
concentration_summary = load_csv(REPORTS_TABLES / "07_concentration_summary.csv", index_col=None)
monitoring_flags = load_csv(REPORTS_TABLES / "07_monitoring_flag_summary.csv", index_col=None)
top_borrowers_el = load_csv(REPORTS_TABLES / "07_top_borrowers_by_expected_loss.csv", index_col=0)
calibration_by_band = load_csv(REPORTS_TABLES / "07_calibration_by_risk_band.csv", index_col=0)

stress_results = load_csv(DATA_PROCESSED / "credit_risk_stress_results.csv", index_col=0)
stress_summary = load_csv(REPORTS_TABLES / "08_portfolio_stress_summary.csv", index_col=None)
risk_band_stress = load_csv(REPORTS_TABLES / "08_risk_band_stress_summary.csv", index_col=None)
cluster_stress = load_csv(REPORTS_TABLES / "08_cluster_stress_summary.csv", index_col=None)
top_severe_stress = load_csv(REPORTS_TABLES / "08_top_severe_stress_borrowers.csv", index_col=0)
stress_scenarios = load_csv(REPORTS_TABLES / "08_stress_scenarios.csv", index_col=None)


# ---------------------------------------------------------------------
# Sidebar
# ---------------------------------------------------------------------

st.sidebar.title("Credit Risk Lab")
st.sidebar.caption("Credit risk dashboard powered by the outputs of the analytical pipeline.")

st.sidebar.markdown("### Data status")

if portfolio_report is not None:
    st.sidebar.success("Portfolio report loaded")
else:
    st.sidebar.error("Portfolio report missing")

if stress_results is not None:
    st.sidebar.success("Stress results loaded")
else:
    st.sidebar.info("Stress testing outputs not found")

st.sidebar.markdown("---")

st.sidebar.markdown("### Filters")

if portfolio_report is not None:
    filtered_portfolio = portfolio_report.copy()

    if "risk_band" in filtered_portfolio.columns:
        risk_bands = sorted(filtered_portfolio["risk_band"].dropna().astype(str).unique().tolist())
        selected_risk_bands = st.sidebar.multiselect(
            "Risk band",
            options=risk_bands,
            default=risk_bands,
        )
        filtered_portfolio = filtered_portfolio[
            filtered_portfolio["risk_band"].astype(str).isin(selected_risk_bands)
        ]

    if "risk_cluster" in filtered_portfolio.columns:
        cluster_options = sorted(filtered_portfolio["risk_cluster"].dropna().astype(str).unique().tolist())
        selected_clusters = st.sidebar.multiselect(
            "Risk cluster",
            options=cluster_options,
            default=cluster_options,
        )
        filtered_portfolio = filtered_portfolio[
            filtered_portfolio["risk_cluster"].astype(str).isin(selected_clusters)
        ]

    if "ensemble_anomaly_flag" in filtered_portfolio.columns:
        anomaly_filter = st.sidebar.selectbox(
            "Anomaly filter",
            options=["All", "Normal profiles", "Anomalous profiles"],
        )

        if anomaly_filter == "Normal profiles":
            filtered_portfolio = filtered_portfolio[filtered_portfolio["ensemble_anomaly_flag"] == 0]
        elif anomaly_filter == "Anomalous profiles":
            filtered_portfolio = filtered_portfolio[filtered_portfolio["ensemble_anomaly_flag"] == 1]
else:
    filtered_portfolio = None


# ---------------------------------------------------------------------
# Header
# ---------------------------------------------------------------------

st.markdown('<div class="main-title">Credit Risk Intelligence Lab</div>', unsafe_allow_html=True)
st.markdown(
    '<div class="subtitle">Probability of Default · Unsupervised Segmentation · Anomaly Detection · Interpretability · Stress Testing</div>',
    unsafe_allow_html=True,
)

if portfolio_report is None:
    show_missing_outputs_message()
    st.stop()


# ---------------------------------------------------------------------
# Tabs
# ---------------------------------------------------------------------

tab_overview, tab_bands, tab_clusters, tab_anomalies, tab_borrowers, tab_stress, tab_methodology = st.tabs(
    [
        "Overview",
        "Risk Bands",
        "Clusters",
        "Anomalies",
        "Borrower Review",
        "Stress Testing",
        "Methodology",
    ]
)


# ---------------------------------------------------------------------
# Overview tab
# ---------------------------------------------------------------------

with tab_overview:
    st.subheader("Portfolio Overview")
    st.markdown(
        """
        <div class="section-caption">
        This section summarizes the main credit risk indicators of the portfolio.
        The dashboard uses the analytical outputs generated by the notebook pipeline.
        </div>
        """,
        unsafe_allow_html=True,
    )

    filtered_n = len(filtered_portfolio) # type: ignore
    filtered_ead = filtered_portfolio["ead_proxy"].sum() if "ead_proxy" in filtered_portfolio.columns else np.nan # type: ignore
    filtered_avg_pd = filtered_portfolio["predicted_pd"].mean() if "predicted_pd" in filtered_portfolio.columns else np.nan # type: ignore
    filtered_el = filtered_portfolio["expected_loss_proxy"].sum() if "expected_loss_proxy" in filtered_portfolio.columns else np.nan # type: ignore
    filtered_el_rate = filtered_el / filtered_ead if filtered_ead and filtered_ead > 0 else np.nan 
    filtered_default_rate = (
        filtered_portfolio["actual_default"].mean() # type: ignore
        if "actual_default" in filtered_portfolio.columns # type: ignore
        else np.nan
    )

    col1, col2, col3, col4, col5 = st.columns(5)

    col1.metric("Borrowers", f"{filtered_n:,}")
    col2.metric("Exposure proxy", format_number(filtered_ead))
    col3.metric("Average PD", format_percent(filtered_avg_pd))
    col4.metric("Observed default", format_percent(filtered_default_rate))
    col5.metric("Expected loss rate", format_percent(filtered_el_rate))

    st.markdown("---")

    left, right = st.columns([1.1, 1])

    with left:
        if risk_band_summary is not None and not risk_band_summary.empty:
            plot_df = risk_band_summary.reset_index()
            safe_bar_chart(
                plot_df,
                x_col="risk_band",
                y_col="expected_loss_share",
                title="Expected Loss Share by Risk Band",
                y_label="Share of total expected loss proxy.",
            )

    with right:
        if cluster_summary is not None and not cluster_summary.empty:
            plot_df = cluster_summary.reset_index()
            safe_bar_chart(
                plot_df,
                x_col="risk_cluster",
                y_col="expected_loss_share",
                title="Expected Loss Share by Risk Cluster",
                y_label="Share of total expected loss proxy.",
            )

    st.markdown("### Portfolio KPI Table")

    if portfolio_kpis is not None:
        st.dataframe(portfolio_kpis, use_container_width=True, hide_index=True)
    else:
        st.info("Portfolio KPI table not found.")

    dataframe_download_button(
        filtered_portfolio, # type: ignore
        label="Download filtered portfolio",
        file_name="filtered_credit_risk_portfolio.csv",
    )


# ---------------------------------------------------------------------
# Risk bands tab
# ---------------------------------------------------------------------

with tab_bands:
    st.subheader("Risk Band Analysis")

    st.markdown(
        """
        <div class="risk-note">
        Risk bands translate raw predicted probabilities into a monitoring structure.
        They are not final underwriting policy rules. They are portfolio reporting groups.
        </div>
        """,
        unsafe_allow_html=True,
    )

    if risk_band_summary is not None:
        st.dataframe(risk_band_summary, use_container_width=True)

        col1, col2 = st.columns(2)

        with col1:
            chart_df = risk_band_summary.reset_index()
            safe_bar_chart(
                chart_df,
                x_col="risk_band",
                y_col="avg_predicted_pd",
                title="Average PD by Risk Band",
                y_label="Average predicted probability of default.",
            )

        with col2:
            chart_df = risk_band_summary.reset_index()
            safe_bar_chart(
                chart_df,
                x_col="risk_band",
                y_col="observed_default_rate",
                title="Observed Default Rate by Risk Band",
                y_label="Observed default rate in the sample.",
            )

        if calibration_by_band is not None:
            st.markdown("### Calibration-style View")
            st.dataframe(calibration_by_band, use_container_width=True)
    else:
        st.info("Risk band summary not found. Run notebook 07.")


# ---------------------------------------------------------------------
# Clusters tab
# ---------------------------------------------------------------------

with tab_clusters:
    st.subheader("Unsupervised Risk Segmentation")

    st.markdown(
        """
        <div class="risk-note">
        The cluster layer groups borrowers according to hidden structure in the processed feature space.
        Clusters are interpreted through PD, observed default, exposure, expected loss, and anomaly rate.
        </div>
        """,
        unsafe_allow_html=True,
    )

    if cluster_summary is not None:
        st.dataframe(cluster_summary, use_container_width=True)

        col1, col2 = st.columns(2)

        with col1:
            chart_df = cluster_summary.reset_index()
            safe_bar_chart(
                chart_df,
                x_col="risk_cluster",
                y_col="avg_predicted_pd",
                title="Average PD by Cluster",
                y_label="Average predicted probability of default by hidden segment.",
            )

        with col2:
            chart_df = cluster_summary.reset_index()
            safe_bar_chart(
                chart_df,
                x_col="risk_cluster",
                y_col="expected_loss_share",
                title="Expected Loss Share by Cluster",
                y_label="Share of expected loss proxy by segment.",
            )
    else:
        st.info("Cluster summary not found. Run notebook 04 and notebook 07.")


# ---------------------------------------------------------------------
# Anomalies tab
# ---------------------------------------------------------------------

with tab_anomalies:
    st.subheader("Anomaly Detection")

    st.markdown(
        """
        <div class="risk-note">
        Anomalous borrowers are not automatically bad borrowers. They are profiles whose combination
        of features is unusual relative to the rest of the portfolio.
        </div>
        """,
        unsafe_allow_html=True,
    )

    if anomaly_summary is not None:
        st.dataframe(anomaly_summary, use_container_width=True)

    if "ensemble_anomaly_flag" in portfolio_report.columns:
        anomaly_rate = portfolio_report["ensemble_anomaly_flag"].mean()
        anomalous_df = portfolio_report[portfolio_report["ensemble_anomaly_flag"] == 1].copy()

        col1, col2, col3 = st.columns(3)

        col1.metric("Anomaly rate", format_percent(anomaly_rate))
        col2.metric("Anomalous borrowers", f"{len(anomalous_df):,}")
        if "expected_loss_proxy" in anomalous_df.columns and "expected_loss_proxy" in portfolio_report.columns:
            anomaly_el_share = anomalous_df["expected_loss_proxy"].sum() / portfolio_report["expected_loss_proxy"].sum()
            col3.metric("Anomaly EL share", format_percent(anomaly_el_share))

        st.markdown("### Top Anomalous Profiles")

        sort_col = "ensemble_anomaly_score" if "ensemble_anomaly_score" in anomalous_df.columns else "predicted_pd"

        review_cols = [
            "ensemble_anomaly_score",
            "ensemble_anomaly_flag",
            "predicted_pd",
            "actual_default",
            "risk_band",
            "risk_cluster",
            "credit_amount",
            "duration_months",
            "age_years",
            "expected_loss_proxy",
        ]

        available_cols = [col for col in review_cols if col in anomalous_df.columns]

        st.dataframe(
            anomalous_df.sort_values(sort_col, ascending=False)[available_cols].head(25),
            use_container_width=True,
        )
    else:
        st.info("Anomaly fields not found. Run notebook 05 and notebook 07.")


# ---------------------------------------------------------------------
# Borrower review tab
# ---------------------------------------------------------------------

with tab_borrowers:
    st.subheader("Borrower Review")

    st.markdown(
        """
        <div class="risk-note">
        This section helps prioritize individual borrower review based on expected loss,
        predicted PD, anomaly score, and risk segment.
        </div>
        """,
        unsafe_allow_html=True,
    )

    sort_options = [
        col for col in [
            "expected_loss_proxy",
            "predicted_pd",
            "ead_proxy",
            "ensemble_anomaly_score",
            "credit_amount",
        ]
        if col in filtered_portfolio.columns # type: ignore
    ]

    sort_col = st.selectbox("Sort borrowers by", options=sort_options, index=0)

    n_rows = st.slider("Number of borrowers to display", min_value=5, max_value=100, value=25, step=5)

    review_cols = [
        "predicted_pd",
        "actual_default",
        "risk_band",
        "risk_cluster",
        "ensemble_anomaly_score",
        "ensemble_anomaly_flag",
        "credit_amount",
        "duration_months",
        "age_years",
        "ead_proxy",
        "expected_loss_proxy",
        "top_positive_contributors",
        "top_negative_contributors",
        "risk_narrative",
    ]

    available_review_cols = [col for col in review_cols if col in filtered_portfolio.columns] # type: ignore

    borrower_review = (
        filtered_portfolio
        .sort_values(sort_col, ascending=False) # type: ignore
        [available_review_cols]
        .head(n_rows)
    )

    st.dataframe(borrower_review, use_container_width=True)

    dataframe_download_button(
        borrower_review,
        label="Download borrower review table",
        file_name="borrower_review.csv",
    )


# ---------------------------------------------------------------------
# Stress testing tab
# ---------------------------------------------------------------------

with tab_stress:
    st.subheader("Stress Testing")

    st.markdown(
        """
        <div class="risk-note">
        Stress testing estimates how portfolio expected loss changes under alternative PD, LGD,
        exposure, and targeted segment deterioration assumptions.
        </div>
        """,
        unsafe_allow_html=True,
    )

    if stress_summary is None:
        st.info("Stress testing outputs not found. Run notebook 08 to activate this tab.")
    else:
        st.markdown("### Scenario Summary")
        st.dataframe(stress_summary, use_container_width=True, hide_index=True)

        col1, col2 = st.columns(2)

        with col1:
            chart_df = stress_summary[["scenario", "total_expected_loss"]].copy()
            safe_bar_chart(
                chart_df,
                x_col="scenario",
                y_col="total_expected_loss",
                title="Total Expected Loss by Scenario",
                y_label="Scenario-level total expected loss proxy.",
            )

        with col2:
            chart_df = stress_summary[["scenario", "expected_loss_rate"]].copy()
            safe_bar_chart(
                chart_df,
                x_col="scenario",
                y_col="expected_loss_rate",
                title="Expected Loss Rate by Scenario",
                y_label="Expected loss divided by stressed EAD.",
            )

        if stress_scenarios is not None:
            st.markdown("### Scenario Assumptions")
            st.dataframe(stress_scenarios, use_container_width=True, hide_index=True)

        if top_severe_stress is not None:
            st.markdown("### Top Borrowers under Severe Stress")
            st.dataframe(top_severe_stress.head(25), use_container_width=True)

        if risk_band_stress is not None:
            st.markdown("### Risk Band Stress Summary")
            st.dataframe(risk_band_stress, use_container_width=True, hide_index=True)

        if cluster_stress is not None:
            st.markdown("### Cluster Stress Summary")
            st.dataframe(cluster_stress, use_container_width=True, hide_index=True)


# ---------------------------------------------------------------------
# Methodology tab
# ---------------------------------------------------------------------

with tab_methodology:
    st.subheader("Methodology")

    st.markdown(
        """
        This dashboard is the product layer of the analytical pipeline. The notebooks are not merely
        theoretical; they are the research, experimentation, validation, and reporting layer. The
        Streamlit app consumes their outputs and translates them into an interactive interface.

        The current first version follows this workflow:

        ```text
        01 EDA
        02 Feature Engineering
        03 Probability of Default Model
        04 Unsupervised Risk Segmentation
        05 Anomaly Detection
        06 Model Interpretability
        07 Portfolio Risk Reporting
        08 Stress Testing
        app/streamlit_app.py
        ```

        Main analytical components:

        - **PD model:** baseline logistic regression for interpretable probability of default.
        - **Segmentation:** K-Means risk clusters over processed borrower features.
        - **Anomaly detection:** Isolation Forest, Local Outlier Factor, and ensemble anomaly score.
        - **Expected loss proxy:** PD × LGD × EAD, using credit amount as exposure proxy.
        - **Stress testing:** scenario-based shocks to PD, LGD, EAD, high-risk bands, clusters, and anomalies.

        Important caveat: the first version uses a compact public dataset. The same app can be extended
        to larger datasets if the upstream pipeline produces the same reporting schema.
        """
    )

    st.markdown("### Required main output schema")

    schema = pd.DataFrame(
        [
            {"column": "predicted_pd", "description": "Model-estimated probability of default."},
            {"column": "actual_default", "description": "Observed target label where available."},
            {"column": "risk_band", "description": "PD-based reporting band."},
            {"column": "risk_cluster", "description": "Unsupervised borrower segment."},
            {"column": "ead_proxy", "description": "Exposure proxy, currently based on credit amount."},
            {"column": "expected_loss_proxy", "description": "PD × LGD × EAD proxy."},
            {"column": "ensemble_anomaly_score", "description": "Combined anomaly score."},
            {"column": "ensemble_anomaly_flag", "description": "Final anomaly flag."},
        ]
    )

    st.dataframe(schema, use_container_width=True, hide_index=True)
